# OPEN API
quarkus.smallrye-openapi.info-title=gestion-ets-API
quarkus.smallrye-openapi.info-version=${project.version}
quarkus.smallrye-openapi.info-description=API Rest que implementa el negocio del calendario de ets en el sistema

quarkus.swagger-ui.theme=original
quarkus.swagger-ui.always-include=true
quarkus.http.cors.origins=http://localhost:3000
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Authorization,Content-Type

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/calendario-ets

mp.jwt.verify.issuer=auth-ets-api
mp.jwt.verify.publickey.algorithm=HS256
mp.jwt.verify.publickey=${JWT_SECRET}
firebase.credentials={FIREBASE_CREDENTIALS}