# OPEN API
quarkus.smallrye-openapi.info-title=gestion-ets-auth-API
quarkus.smallrye-openapi.info-version=${project.version}
quarkus.smallrye-openapi.info-description=API Rest que implementa el negocio del usuario en el sistema
quarkus.swagger-ui.theme=original
quarkus.swagger-ui.always-include=true

quarkus.http.cors.origins=http://localhost:3000
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Authorization,Content-Type

quarkus.datasource.username=${PGUSER}
quarkus.datasource.password=${PGPASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
quarkus.mailer.auth-methods=PLAIN
quarkus.mailer.from=escomprueba21@gmail.com
quarkus.mailer.host=smtp.gmail.com
quarkus.mailer.port=587
quarkus.mailer.start-tls=REQUIRED
quarkus.mailer.username=escomprueba21@gmail.com
quarkus.mailer.password=irri yxcf jzkj lnom
quarkus.mailer.mock=false

quarkus.rest-client.resend-api.url=https://api.resend.com
resend.api.key=${RESEND_API_KEY}
resend.from=onboarding@resend.dev
app.deeplink.base-url=${APP_CONFIRMACION}
app.forgotpassword.base-url=${APP_OLVIDAR_CONTRASENIA}
mp.jwt.verify.issuer=auth-ets-api
resend.to.override=escomprueba21@gmail.com
# Duraci�n del access token en segundos (15 min)
jwt.access.duration=900
jwt.refresh.duration=604800
quarkus.http.port = ${PORT_AUTH}

# Validación de tokens entrantes
quarkus.http.auth.permission.public.paths=/auth/*,/q/health/*,/q/openapi,/q/swagger-ui/*
quarkus.http.auth.permission.public.policy=permit


# Resto requiere autenticaci�n
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated
